@startuml
'https://plantuml.com/activity-diagram-beta

start

:last = 1;
:preLAst = 1;
:result = 1;
if(PosOfSeq <= 0?)) then (yes)
stop;
else(no)
while(PosOfSeq > 1)
    :result += last + preLast;
    :preLast = last;
    :last = result;
    :posOfSeq--;
endwhile;
stop;
@enduml
