@startuml
'https://plantuml.com/activity-diagram-beta

start
repeat ;
if(posOfSeq < 2?) then(yes)
    :standard case
         return n;
    stop;
else(no)
    :return fib(n-1) + fib(n-2);
endif;
fork
        :n-1;
fork again
        :n-2;
    end fork;
:call recursive functions;
@enduml
